services:
  app:
    build: ./
    ports:
      - 4000:4000
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - 27018:27017